# Generated by Django 5.0.6 on 2024-05-16 15:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='The academic year, e.g., 2024')),
                ('term', models.CharField(help_text='E.g., Fall, Spring, Summer', max_length=100)),
                ('credit_limit', models.IntegerField(help_text='Maximum credits a student can enroll in this semester.')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField(default=30, help_text='Maximum number of students that can enroll.')),
                ('offered_semesters', models.ManyToManyField(related_name='subjects', to='studyplan.semester')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='studyplan.university')),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='studyplan.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='authorization.userprofile')),
                ('subjects', models.ManyToManyField(related_name='study_plans', to='studyplan.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=9)),
                ('start_time', models.TimeField(help_text='Start time of the class')),
                ('end_time', models.TimeField(help_text='End time of the class')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyplan.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyplan.subject')),
            ],
            options={
                'unique_together': {('subject', 'semester', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=9)),
                ('start_time', models.TimeField(default=datetime.time(12, 0), help_text='Start time of the class')),
                ('end_time', models.TimeField(default=datetime.time(13, 0), help_text='End time of the class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='authorization.userprofile')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='studyplan.semester')),
                ('subject_semester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='studyplan.subjectsemester')),
            ],
            options={
                'unique_together': {('student', 'semester', 'day_of_week', 'start_time')},
            },
        ),
    ]
