# Generated by Django 5.0.6 on 2024-05-15 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('studyplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=9)),
                ('time', models.TimeField(help_text='Start time of the class')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='studyplan.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='authorization.userprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='studyplan.subject')),
            ],
            options={
                'unique_together': {('student', 'semester', 'day_of_week', 'time')},
            },
        ),
    ]
