# Generated by Django 5.0.6 on 2024-05-16 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('studyplan', '0003_alter_semester_term_faculty_subject_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='studyplan.university'),
        ),
    ]
